### ISSUE TITLE
Why are TikZ pictures built separately?

### ISSUE THREAD

**Issue by cedounet** [hendricius/the-sourdough-framework#115] opened 2023-06-04 19:25 UTC
Is there a reason for that?  Tables were the same but looks like this wasn't really needed any more (or I missed the reason) having them built with the tex file would make them searchable.

Thanks

**Comment by hendricius** [comment] 2023-06-05 08:21
Good question! The problem was that sometimes the tikzpictures were not properly displayed in the resulting epub versions. The problem is that not all of them display the SVG properly. That's why it was easier to include the final pictures in the book. It worked well when I generated `epub3` files but then not all readers support this format.

**Comment by hendricius** [comment] 2023-06-08 09:22
I will close this for now, we can re-open the issue later if needed!

**Closed by hendricius** 2023-06-08 09:22 UTC
